# -*- coding: utf-8 -*-
"""python class 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJZtqgCMG7OND7uSmKI93wA3JVMCCtWE
"""

#list datatype
#collection of values
#ordered and mutable
a=[1,2,3,'abc']
type(a)

a[2:5]

a[0]=2
print(a)

a[2:4]=['a','b']
print(a)

#append insert single element at a time at the end of a list
a.append(7)
print(a)

#extend add multiple elements at the end of the list
a.extend([8,9])
print(a)

#pop delete element
# if we do not pass any value inside pop,it will remove the last element from the list

#loop on list directly
for i in [10,20,30,'a']:
  print(i)

a=[1,1,2,3,4,5]
len(a)

b=[10,20,4,5,21,88]
for i in range(1,6):
  if (b[i]%2==0):
    print(b[i])

b=[10,20,4,5,21,88]
for i in range(1,6):
  if i%2==0:
   print(i, b[i])

a=[1,2,4,7,9,'a']
b=[]
for i in a:
  if type(i) is int:
   b.append(i*i)
print(b)

x=11
list=[10,12,113,11,11,200]
if x in list:
  print(True)
else:
  print(False)

list=[10,12,113,11,11,200]
x=0
for i in range(0,len(list)):
  for j in range(i+1,len(list)):
     if list[i]==list[j]:
      x+=1
      break
if x==1:
      print("duplicate")

a=[1, 2, 3, 2, 4, 5, 3, 6, 1]
for i in range(0,len(a)):
  for j in range(i+1,len(a)):
    if a[i]==a[j]:
     print("duplicate")

list=[10,12,113,11,11,11,200]
x=0
a=[]
for i in range(0,len(list)):
  for j in range(i+1,len(list)):
     if list[i]==list[j]:
      if list[i] not in a:
       a.append(list[i])
       print(a)

num=1
n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    if j==1 or i==n or i==j:
      print(num,end=" ")
      num+=1
    else:
      print(" ",end=" ")
  print()

n=153
sum=0
temp=n
while n>0:
  r=n%10
  sum+=r**3
  n//=10
if sum==temp:
  print("Narcissistic number")
else:
  print("not")

n=1634
sum=0
temp=n
while n>0:
  r=n%10
  sum+=r**4
  n//=10
if sum==temp:
  print("Narcissistic number")
else:
  print("not")

a=[10,5,8,9,16,18]
b=[]
max=a[0]
for i in a:
  if i>max:
    max=i
print(max)